apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: mongodb-pv-claim-01
    labels:
      app: mongodb
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: mongodb-pv-claim-02
    labels:
      app: mongodb
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1000Gi

